<a href="https://colab.research.google.com/github/ma-shamshiri/Basic-Libs/blob/master/List%20vs%20Array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [3]:
L = [1,2,3]
L

[1, 2, 3]

In [4]:
A = np.array([1,2,3])
A

array([1, 2, 3])

In [5]:
L + [1]
L

[1, 2, 3]

In [6]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: ignored

In [8]:
L + [5]

[1, 2, 3, 4, 5]

In [9]:
A + 5

array([6, 7, 8])

In [0]:
L2 = []
for i in L:
  L2.append(i + 5)

In [11]:
L2

[6, 7, 8, 9]

In [12]:
L2 = [i+5 for i in L]
L2

[6, 7, 8, 9]

In [0]:
L * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [0]:
L + L

[1, 2, 3, 4, 1, 2, 3, 4]

In [0]:
A * 2

array([2, 4, 6])

In [0]:
A * [2,3,4]

array([ 2,  6, 12])

In [13]:
L ** 2

TypeError: ignored

In [15]:
L2 = [i**2 for i in L]
L2

[1, 4, 9, 16]

In [0]:
A ** 2

array([1, 4, 9])

In [16]:
np.sqrt(A)

array([1.        , 1.41421356, 1.73205081])

In [20]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

# New Section

In [17]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [18]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])